### ISSUE TITLE
Use an init-container for celestia app state in favour of two bind mounts

### ISSUE THREAD

**Issue by damiannolan** [celestiaorg/celestia-zkevm-hl-testnet#39]
This uses the same bind mount hack for reproducible chain state which is used in the existing ibc setup.

Is there any reason not to use something like an init-container and named docker volume instead? IMO might be cleaner

e.g. something like this... if a genesis.json exists then skip init container steps (allows stop/start functionality without compromising state), otherwise a genesis.json doesn't exist - initialise chain state and test keyring.

```yaml
celestia-init:
    image: ghcr.io/celestiaorg/celestia-app-standalone:02ff9af
    container_name: celestia-init
    entrypoint: sh -c
    command: >
      if [ ! -f /root/.celestia-app/config/genesis.json ]; then
        echo "Initializing Celestia state...";
        celestia-appd init zkevm-test --chain-id celestia-zkevm-testnet &&
        # init keys, gen accs and gen txs...
        celestia-appd genesis collect-gentxs &&
        celestia-appd genesis validate &&
        echo "Init complete.";
      else
        echo "Skipping init, genesis.json already exists.";
      fi
    volumes:
      - celestia-state:/home/celestia/.celestia-app
    restart: "no"
```

Then we do a `depends_on` like:
```yaml
depends_on:
      celestia-init:
        condition: service_completed_successfully
```

_Originally posted by @damiannolan in https://github.com/celestiaorg/celestia-zkevm-hl-testnet/pull/38#discussion_r2073289929_
